// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// bm_cpp_icl_partition
List bm_cpp_icl_partition(IntegerMatrix x, IntegerVector sets, IntegerVector k, List clu, bool symmetric, double epsilon, double epsilonTrans);
RcppExport SEXP _dynGLMbm_bm_cpp_icl_partition(SEXP xSEXP, SEXP setsSEXP, SEXP kSEXP, SEXP cluSEXP, SEXP symmetricSEXP, SEXP epsilonSEXP, SEXP epsilonTransSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type sets(setsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type k(kSEXP);
    Rcpp::traits::input_parameter< List >::type clu(cluSEXP);
    Rcpp::traits::input_parameter< bool >::type symmetric(symmetricSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< double >::type epsilonTrans(epsilonTransSEXP);
    rcpp_result_gen = Rcpp::wrap(bm_cpp_icl_partition(x, sets, k, clu, symmetric, epsilon, epsilonTrans));
    return rcpp_result_gen;
END_RCPP
}
// bm_cpp_optimize_partition
List bm_cpp_optimize_partition(IntegerMatrix x, IntegerVector sets, IntegerVector k, List clu, bool symmetric, bool verbose, double epsilon, double epsilonTrans, int mincluster, int maxiter, double chng_ratio, int maxRuns, int maxNoImp);
RcppExport SEXP _dynGLMbm_bm_cpp_optimize_partition(SEXP xSEXP, SEXP setsSEXP, SEXP kSEXP, SEXP cluSEXP, SEXP symmetricSEXP, SEXP verboseSEXP, SEXP epsilonSEXP, SEXP epsilonTransSEXP, SEXP minclusterSEXP, SEXP maxiterSEXP, SEXP chng_ratioSEXP, SEXP maxRunsSEXP, SEXP maxNoImpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type sets(setsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type k(kSEXP);
    Rcpp::traits::input_parameter< List >::type clu(cluSEXP);
    Rcpp::traits::input_parameter< bool >::type symmetric(symmetricSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< double >::type epsilonTrans(epsilonTransSEXP);
    Rcpp::traits::input_parameter< int >::type mincluster(minclusterSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< double >::type chng_ratio(chng_ratioSEXP);
    Rcpp::traits::input_parameter< int >::type maxRuns(maxRunsSEXP);
    Rcpp::traits::input_parameter< int >::type maxNoImp(maxNoImpSEXP);
    rcpp_result_gen = Rcpp::wrap(bm_cpp_optimize_partition(x, sets, k, clu, symmetric, verbose, epsilon, epsilonTrans, mincluster, maxiter, chng_ratio, maxRuns, maxNoImp));
    return rcpp_result_gen;
END_RCPP
}
// bm_cpp_multiple_optimize
List bm_cpp_multiple_optimize(IntegerMatrix x, IntegerVector sets, IntegerVector k, int runs, bool symmetric, bool verbose, double epsilon, double epsilonTrans, int mincluster, int maxiter, double chng_ratio, int maxRuns, int maxNoImp);
RcppExport SEXP _dynGLMbm_bm_cpp_multiple_optimize(SEXP xSEXP, SEXP setsSEXP, SEXP kSEXP, SEXP runsSEXP, SEXP symmetricSEXP, SEXP verboseSEXP, SEXP epsilonSEXP, SEXP epsilonTransSEXP, SEXP minclusterSEXP, SEXP maxiterSEXP, SEXP chng_ratioSEXP, SEXP maxRunsSEXP, SEXP maxNoImpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type sets(setsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type runs(runsSEXP);
    Rcpp::traits::input_parameter< bool >::type symmetric(symmetricSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< double >::type epsilonTrans(epsilonTransSEXP);
    Rcpp::traits::input_parameter< int >::type mincluster(minclusterSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< double >::type chng_ratio(chng_ratioSEXP);
    Rcpp::traits::input_parameter< int >::type maxRuns(maxRunsSEXP);
    Rcpp::traits::input_parameter< int >::type maxNoImp(maxNoImpSEXP);
    rcpp_result_gen = Rcpp::wrap(bm_cpp_multiple_optimize(x, sets, k, runs, symmetric, verbose, epsilon, epsilonTrans, mincluster, maxiter, chng_ratio, maxRuns, maxNoImp));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_dynGLMbm_bm_cpp_icl_partition", (DL_FUNC) &_dynGLMbm_bm_cpp_icl_partition, 7},
    {"_dynGLMbm_bm_cpp_optimize_partition", (DL_FUNC) &_dynGLMbm_bm_cpp_optimize_partition, 13},
    {"_dynGLMbm_bm_cpp_multiple_optimize", (DL_FUNC) &_dynGLMbm_bm_cpp_multiple_optimize, 13},
    {NULL, NULL, 0}
};

RcppExport void R_init_dynGLMbm(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
