# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bm_cpp_icl_partition <- function(x, sets, k, clu, symmetric, epsilon, epsilonTrans) {
    .Call(`_dynGLMbm_bm_cpp_icl_partition`, x, sets, k, clu, symmetric, epsilon, epsilonTrans)
}

bm_cpp_optimize_partition <- function(x, sets, k, clu, symmetric, verbose, epsilon, epsilonTrans, mincluster, maxiter, chng_ratio, maxRuns, maxNoImp) {
    .Call(`_dynGLMbm_bm_cpp_optimize_partition`, x, sets, k, clu, symmetric, verbose, epsilon, epsilonTrans, mincluster, maxiter, chng_ratio, maxRuns, maxNoImp)
}

bm_cpp_multiple_optimize <- function(x, sets, k, runs, symmetric, verbose, epsilon, epsilonTrans, mincluster, maxiter, chng_ratio, maxRuns, maxNoImp) {
    .Call(`_dynGLMbm_bm_cpp_multiple_optimize`, x, sets, k, runs, symmetric, verbose, epsilon, epsilonTrans, mincluster, maxiter, chng_ratio, maxRuns, maxNoImp)
}

